export default [
/*-------Paris--------*/
{ 
  id: 1,
  url:'image/pris-c-01.jpg',
  city: 'Paris, França',
  gender: 'child',
  description:  {
    pt: "Roupas coloridas e unissex",
    en: "Colorfull and unissex clothes",
    es: "Ropa colorida y unissex",
    it: "Abiti colorati e unissex"
  },
  price: 12,
  dateStart: '24/12/2019',
  dateEnd: '28/12/2019',
  sign: '£',
  language: 'en',
}, {
  id: 2,
  url:'image/paris-c-02.jpg',
  city: 'Paris, França',
  gender: 'child',
  description:  {
    pt: "Charme, delicadeza e diversão",
    en: "Charm, delicate and fun",
    es: "Encanto, delicado y divertido",
    it: "Fascino, delicato e divertente"
  },
  price: 9,
  dateStart: '13/12/2019',
  dateEnd: '28/02/2020',
  sign: '£',
  language: 'en',

},{
  id: 3,
  url:'image/ciranda-094.jpg',
  city: 'Paris, França',
  gender: 'child',
  description:  {
    pt: "Artesanal. delicado e doce",
    en: "Handmade, delicate and sweet",
    es: "Hecho a mano, delicado y dulce",
    it: "Fatto a mano, delicato e dolce"
  },
 
  price: 8,
  dateStart: '30/12/2019',
  dateEnd: '05/01/2020',
  sign: '£',
  language: 'en',
},
{ id: 4,
  url:'image/paris-f-01.jpg',
  city: 'Paris, França',
  gender: 'female',
  description:  {
    pt: "Charme, elegancia e conforto",
    en: "charm, fancy and comfortable",
    es: "encanto, elegante y confortable",
    it: "Affascinante, elegante e confortevole"
  },
  price: 15,
  dateStart: '15/12/2019',
  dateEnd: '18/12/2019',
  sign: '£',
  language: 'en',},

{ id: 5,
  url:'image/paris-f-02.jpg',
  city: 'Paris, França',
  gender: 'female',
  description:  {
    pt: "Moderno, artesanal e elegante",
    en: "Modern, handmade and elegant",
    es: "Moderno, artesanal y elegante",
    it: "Moderno, fatto a mano ed elegante"
  },
 
  price: 30,
  dateStart: '15/02/2020',
  dateEnd: '25/02/2020',
  sign: '£',
  language: 'en',},
{ id: 6,
  url:'image/paris-f-03.jpg',
  city: 'Paris, França',
  gender: 'female',
  description:  {
    pt: "Confortável, moderno e charmoso",
    en: "Comfortable, modern and charm",
    es: "Cómodo, moderno y con encanto",
    it: "Confortevole, moderno e affascinante"
  },
  price: 7,
  dateStart: '08/03/2020',
  dateEnd: '01/04/2020',
  sign: '£',
  language: 'en',},
{ id: 7,
  url:'image/paris-m-01.jpg',
  city: 'Paris, França',
  gender: 'male',
  description:  {
    pt: "Confortável e moderno",
    en: "Comfortable and modern",
    es: "Cómodo y moderno",
    it: "Confortevole e moderno"
  },
  price: 20,
  dateStart: '20/12/2019',
  dateEnd: '07/01/2020',
  sign: '£',
  language: 'en',},
{ id: 8,
  url:'image/paris-m-02.jpg',
  city: 'Paris, França',
  gender: 'male',
  description:  {
    pt: "Estilo e elegancia",
    en: "Elegant and style",
    es: "Elegante y estilo",
    it: "Elegante e di stile"
  },
  price: 18,
  dateStart: '15/01/2020',
  dateEnd: '17/01/2020',
  sign: '£',
  language: 'en',},
/*-------London--------*/
{
  id: 9,
  url:'image/london-c-01.jpg',
  city: 'London, Reino Unido',
  gender: 'child',
  description:  {
    pt: "Roupas coloridas e unissex",
    en: "Colorfull and unissex clothes",
    es: "Ropa colorida y unissex",
    it: "Abiti colorati e unissex"
  },
  price: 10,
  dateStart: '23/12/2019',
  dateEnd: '26/12/2019',
  sign: '£',
  language: 'en',
  
},{
  id: 10,
  url:'image/ciranda-002.jpg',
  city: 'London, Reino Unido',
   description:  {
    pt: "Charme, delicadeza e diversão",
    en: "Charm, delicate and fun",
    es: "Encanto, delicado y divertido",
    it: "Fascino, delicato e divertente"
  },
  gender: 'child',
  price: 7,
  dateStart: '4/01/2020',
  dateEnd: '8/01/2020',
  sign: '£',
  language: 'en',
  
},
{ id: 11,
  url:'image/london-c-03.jpg',
  city: 'London, Reino Unido',
  description:  {
    pt: "Artesanal. delicado e doce",
    en: "Handmade, delicate and sweet",
    es: "Hecho a mano, delicado y dulce",
    it: "Fatto a mano, delicato e dolce"
  },
  gender: 'child',
  price: 11,
  dateStart: '8/01/2020',
  dateEnd: '17/01/2020',
  sign: '£',
  language: 'en',},
{ id: 12,
  url:'image/london-f-01.jpg',
  city: 'London, Reino Unido',
   description:  {
    pt: "Charme, elegancia e conforto",
    en: "charm, fancy and comfortable",
    es: "encanto, elegante y confortable",
    it: "Affascinante, elegante e confortevole"
  },
  gender: 'female',
  price: 17,
  dateStart: '8/03/2020',
  dateEnd: '10/03/2020',
  sign: '£',
  language: 'en',},
{ id: 13,
  url:'image/london-f-02.jpg',
  city: 'London, Reino Unido',
  description:  {
    pt: "Moderno, artesanal e elegante",
    en: "Modern, handmade and elegant",
    es: "Moderno, artesanal y elegante",
    it: "Moderno, fatto a mano ed elegante"
  },
  gender: 'female',
  price: 25,
  dateStart: '15/01/2020',
  dateEnd: '28/01/2020',
  sign: '£',
  language: 'en',},
{ id: 14,
  url:'image/london-f-03.jpg',
  city: 'London, Reino Unido',
   description:  {
    pt: "Confortável, moderno e charmoso",
    en: "Comfortable, modern and charm",
    es: "Cómodo, moderno y con encanto",
    it: "Confortevole, moderno e affascinante"
  },
  gender: 'female',
  price: 30,
  dateStart: '14/12/2019',
  dateEnd: '23/12/2019',
  sign: '£',
  language: 'en',},
{ id: 15,
  url:'image/london-m-01.jpg',
  city: 'London, Reino Unido',
  description:  {
    pt: "Confortável e moderno",
    en: "Comfortable and modern",
    es: "Cómodo y moderno",
    it: "Confortevole e moderno"
  },
  gender: 'male',
  price: 12,
  dateStart: '27/07/2020',
  dateEnd: '30/07/2020',
  sign: '£',
  language: 'en',},
{ id: 16,
  url:'image/london-m-02.jpg',
  city: 'London, Reino Unido',
  description:  {
    pt: "Estilo e elegancia",
    en: "Elegant and style",
    es: "Elegante y estilo",
    it: "Elegante e di stile"
  },
  gender: 'male',
  price: 5,
  dateStart: '4/04/2020',
  dateEnd: '8/04/2020',
  sign: '£',
  language: 'en',},
/*-------Barcelona-------*/
{
  id: 17,
  url:'image/ciranda-142.jpg',
  city: 'Barcelona, Espanha',
  gender: 'child',
  description:  {
    pt: "Roupas coloridas e unissex",
    en: "Colorfull and unissex clothes",
    es: "Ropa colorida y unissex",
    it: "Abiti colorati e unissex"
  },
  sign: '£',
  price: 20,
  language: 'en',
  dateStart: '24/12/2019',
  dateEnd: '28/12/2019'
  
},
{ id: 18,
  url:'image/ciranda-023.jpg',
  city: 'Barcelona, Espanha',
  gender: 'child',
   description:  {
    pt: "Charme, delicadeza e diversão",
    en: "Charm, delicate and fun",
    es: "Encanto, delicado y divertido",
    it: "Fascino, delicato e divertente"
  },
  sign: '£',
  price: 20,
  language: 'en',
  dateStart: '24/12/2019',
  dateEnd: '28/12/2019'},
{ id: 19,
  url:'image/barcelona-c-01.jpg',
  city: 'Barcelona, Espanha',
  gender: 'child',
  description:  {
    pt: "Artesanal. delicado e doce",
    en: "Handmade, delicate and sweet",
    es: "Hecho a mano, delicado y dulce",
    it: "Fatto a mano, delicato e dolce"
  },
  sign: '£',
  price: 4,
  language: 'en',
  dateStart: '24/02/2020',
  dateEnd: '01/05/2020'},
{ id: 20,
  url:'image/barcelona-m-02.jpg',
  city: 'Barcelona, Espanha',
  gender: 'male',
  description:  {
    pt: "Confortável e moderno",
    en: "Comfortable and modern",
    es: "Cómodo y moderno",
    it: "Confortevole e moderno"
  },
  sign: '£',
  price: 13,
  language: 'en',
  dateStart: '07/12/2019',
  dateEnd: '13/12/2019'},
{ id: 21,
  url:'image/barcelona-f-01.jpg',
  city: 'Barcelona, Espanha',
  gender: 'female',
  description:  {
    pt: "Charme, elegancia e conforto",
    en: "charm, fancy and comfortable",
    es: "encanto, elegante y confortable",
    it: "Affascinante, elegante e confortevole"
  },
  sign: '£',
  price: 28,
  language: 'en',
  dateStart: '20/12/2019',
  dateEnd: '30/12/2019'},
{ id: 22,
  url:'image/barcelona-f-02.jpg',
  city: 'Barcelona, Espanha',
  gender: 'female',
  description:  {
    pt: "Moderno, artesanal e elegante",
    en: "Modern, handmade and elegant",
    es: "Moderno, artesanal y elegante",
    it: "Moderno, fatto a mano ed elegante"
  },
  sign: '£',
  price: 45,
  language: 'en',
  dateStart: '14/01/2020',
  dateEnd: '19/01/2020'},
{ id: 23,
  url:'image/barcelona-f-03.jpg',
  city: 'Barcelona, Espanha',
  gender: 'female',
   description:  {
    pt: "Confortável, moderno e charmoso",
    en: "Comfortable, modern and charm",
    es: "Cómodo, moderno y con encanto",
    it: "Confortevole, moderno e affascinante"
  },
  sign: '£',
  price: 12,
  language: 'en',
  dateStart: '02/02/2020',
  dateEnd: '28/02/2020'},
{ id: 24,
  url:'image/barcelona-m-01.jpg',
  city: 'Barcelona, Espanha',
  gender: 'male',
  description:  {
    pt: "Estilo e elegancia",
    en: "Elegant and style",
    es: "Elegante y estilo",
    it: "Elegante e di stile"
  },
  sign: '£',
  price: 14,
  language: 'en',
  dateStart: '24/12/2019',
  dateEnd: '28/12/2019'},

/*-------Madrid--------*/
{
  id: 25,
  url:'image/madrid-c-01.jpg',
  city: 'Madrid, Espanha',
  gender: 'child',
  description:  {
    pt: "Roupas coloridas e unissex",
    en: "Colorfull and unissex clothes",
    es: "Ropa colorida y unissex",
    it: "Abiti colorati e unissex"
  },
  price: 13,
  sign: '£',
  language: 'en',
  dateStart: '14/12/2019',
  dateEnd: '18/12/2019'},
{ id: 26,url:'image/madrid-c-02.jpg',
city: 'Madrid, Espanha',
gender: 'child',
 description:  {
    pt: "Charme, delicadeza e diversão",
    en: "Charm, delicate and fun",
    es: "Encanto, delicado y divertido",
    it: "Fascino, delicato e divertente"
  },
price: 9,
sign: '£',
language: 'en',
dateStart: '05/01/2020',
dateEnd: '09/01/2020'},
{ id: 27,url:'image/madrid-c-03.jpg',
city: 'Madrid, Espanha',
gender: 'child',
description:  {
    pt: "Artesanal. delicado e doce",
    en: "Handmade, delicate and sweet",
    es: "Hecho a mano, delicado y dulce",
    it: "Fatto a mano, delicato e dolce"
  },
price: 23,
sign: '£',
language: 'en',
dateStart: '02/02/2020',
dateEnd: '08/02/2020'},
{ id: 28,url:'image/madrid-f-01.jpg',
city: 'Madrid, Espanha',
gender: 'female',
description:  {
    pt: "Charme, elegancia e conforto",
    en: "charm, fancy and comfortable",
    es: "encanto, elegante y confortable",
    it: "Affascinante, elegante e confortevole"
  },
price: 25,
sign: '£',
language: 'en',
dateStart: '04/06/2020',
dateEnd: '18/06/2020'},
{ id: 29,url:'image/madrid-f-02.jpg',
city: 'Madrid, Espanha',
gender: 'female',
description: 'Modern, handmade and elegant',
price: 18,
sign: '£',
language: 'en',
dateStart: '06/08/2020',
dateEnd: '17/08/2020'},
{ id: 30,url:'image/madrid-f-03.jpg',
city: 'Madrid, Espanha',
gender: 'female',
 description:  {
    pt: "Confortável, moderno e charmoso",
    en: "Comfortable, modern and charm",
    es: "Cómodo, moderno y con encanto",
    it: "Confortevole, moderno e affascinante"
  },
price: 8,
sign: '£',
language: 'en',
dateStart: '23/12/2019',
dateEnd: '26/12/2019'},
{ id: 31,url:'image/madrid-m-01.jpg',
city: 'Madrid, Espanha',
gender: 'male',
description:  {
    pt: "Confortável e moderno",
    en: "Comfortable and modern",
    es: "Cómodo y moderno",
    it: "Confortevole e moderno"
  },
price: 33,
sign: '£',
language: 'en',
dateStart: '24/12/2019',
dateEnd: '29/12/2019'},
{ id: 32,url:'image/madrid-m-02.jpg',
city: 'Madrid, Espanha',
gender: 'male',
 description:  {
    pt: "Estilo e elegancia",
    en: "Elegant and style",
    es: "Elegante y estilo",
    it: "Elegante e di stile"
  },
price: 12,
sign: '£',
language: 'en',
dateStart: '30/12/2019',
dateEnd: '02/01/2020'},
/*-------Florianópolis--------*/
{
  id: 33,
  url:'image/ciranda-002.jpg',
  city: 'Florianópolis, SC, Brasil',
  gender: 'child',
  description:  {
    pt: "Roupas coloridas e unissex",
    en: "Colorfull and unissex clothes",
    es: "Ropa colorida y unissex",
    it: "Abiti colorati e unissex"
  },
  price:6,
  dateStart: '26/12/2019',
  dateEnd: '30/12/2019',
  sign: '£',
  language: 'en',
  
},
{ id: 34,
  url:'image/florianopolis-c-01.jpg',
  city: 'Florianópolis, SC, Brasil',
  gender: 'child',
   description:  {
    pt: "Charme, delicadeza e diversão",
    en: "Charm, delicate and fun",
    es: "Encanto, delicado y divertido",
    it: "Fascino, delicato e divertente"
  },
  price: 15,
  dateStart: '28/12/2019',
  dateEnd: '02/01/2020',
  sign: '£',
  language: 'en',},
{ id: 35,
  url:'image/florianopolis-c-02.jpg',
  city: 'Florianópolis, SC, Brasil',
  gender: 'child',
  description:  {
    pt: "Artesanal. delicado e doce",
    en: "Handmade, delicate and sweet",
    es: "Hecho a mano, delicado y dulce",
    it: "Fatto a mano, delicato e dolce"
  },
  price: 23,
  dateStart: '04/01/2020',
  dateEnd: '07/01/2020',
  sign: '£',
  language: 'en',},
{ id: 36,
  url:'image/florianopolis-f-01.jpg',
  city: 'Florianópolis, SC, Brasil',
  gender: 'female',
  description:  {
    pt: "Charme, elegancia e conforto",
    en: "charm, fancy and comfortable",
    es: "encanto, elegante y confortable",
    it: "Affascinante, elegante e confortevole"
  },
  price: 17,
  dateStart: '06/01/2020',
  dateEnd: '09/01/2020',
  sign: '£',
  language: 'en',},
{ id: 37,
  url:'image/florianopolis-f-02.jpg',
  city: 'Florianópolis, SC, Brasil',
  gender: 'female',
  description:  {
    pt: "Moderno, artesanal e elegante",
    en: "Modern, handmade and elegant",
    es: "Moderno, artesanal y elegante",
    it: "Moderno, fatto a mano ed elegante"
  },
  price: 43,
  dateStart: '08/01/2020',
  dateEnd: '11/01/2020',
  sign: '£',
  language: 'en',},
{ id: 38,
  url:'image/florianopolis-f-03.jpg',
  city: 'Florianópolis, SC, Brasil',
  gender: 'female',
   description:  {
    pt: "Confortável, moderno e charmoso",
    en: "Comfortable, modern and charm",
    es: "Cómodo, moderno y con encanto",
    it: "Confortevole, moderno e affascinante"
  },
  price: 11,
  dateStart: '12/01/2020',
  dateEnd: '18/01/2020',
  sign: '£',
  language: 'en',},
{ id: 39,
  url:'image/florianopolis-m-01.jpg',
  city: 'Florianópolis, SC, Brasil',
  gender: 'male',
  description:  {
    pt: "Confortável e moderno",
    en: "Comfortable and modern",
    es: "Cómodo y moderno",
    it: "Confortevole e moderno"
  },
  price: 17,
  dateStart: '14/01/2020',
  dateEnd: '20/01/2020',
  sign: '£',
  language: 'en',},
{ id: 40,
  url:'image/florianopolis-m-02.jpg',
  city: 'Florianópolis, SC, Brasil',
  gender: 'male',
   description:  {
    pt: "Estilo e elegancia",
    en: "Elegant and style",
    es: "Elegante y estilo",
    it: "Elegante e di stile"
  },
  price: 12,
  dateStart: '16/01/2020',
  dateEnd: '22/01/2020',
  sign: '£',
  language: 'en',},
/*-------Rio de Janeiro--------*/
{ id: 41,
  url:'image/rio-c-01.jpg',
  city: 'Rio de Janeiro, RJ, Brasil',
  gender: 'child',
  description:  {
    pt: "Roupas coloridas e unissex",
    en: "Colorfull and unissex clothes",
    es: "Ropa colorida y unissex",
    it: "Abiti colorati e unissex"
  },
  price: 14,
  dateStart: '18/01/2020',
  dateEnd: '25/01/2020',
  sign: '£',
  language: 'en',},
{ id: 42,
  url:'image/rio-c-02.jpg',
  city: 'Rio de Janeiro, RJ, Brasil',
  gender: 'child',
   description:  {
    pt: "Charme, delicadeza e diversão",
    en: "Charm, delicate and fun",
    es: "Encanto, delicado y divertido",
    it: "Fascino, delicato e divertente"
  },
  price: 22,
  dateStart: '20/01/2020',
  dateEnd: '28/01/2020',
  sign: '£',
  language: 'en',},
{ id: 43,
  url:'image/rio-c-03.jpg',
  city: 'Rio de Janeiro, RJ, Brasil',
  gender: 'child',
  description:  {
    pt: "Artesanal. delicado e doce",
    en: "Handmade, delicate and sweet",
    es: "Hecho a mano, delicado y dulce",
    it: "Fatto a mano, delicato e dolce"
  },
  price: 18,
  dateStart: '22/01/2020',
  dateEnd: '30/01/2020',
  sign: '£',
  language: 'en',},
{ id: 44,
  url:'image/rio-f-01.jpg',
  city: 'Rio de Janeiro, RJ, Brasil',
  gender: 'female',
  description:  {
    pt: "Charme, elegancia e conforto",
    en: "charm, fancy and comfortable",
    es: "encanto, elegante y confortable",
    it: "Affascinante, elegante e confortevole"
  },
  price: 51,
  dateStart: '02/02/2020',
  dateEnd: '07/02/2020',
  sign: '£',
  language: 'en',},
{ id: 45,
  url:'image/rio-f-02.jpg',
  city: 'Rio de Janeiro, RJ, Brasil',
  gender: 'female',
  description:  {
    pt: "Moderno, artesanal e elegante",
    en: "Modern, handmade and elegant",
    es: "Moderno, artesanal y elegante",
    it: "Moderno, fatto a mano ed elegante"
  },
  price: 17,
  dateStart: '05/02/2020',
  dateEnd: '09/02/2020',
  sign: '£',
  language: 'en',},
{ id: 46,
  url:'image/rio-f-03.jpg',
  city: 'Rio de Janeiro, RJ, Brasil',
  gender: 'female',
   description:  {
    pt: "Confortável, moderno e charmoso",
    en: "Comfortable, modern and charm",
    es: "Cómodo, moderno y con encanto",
    it: "Confortevole, moderno e affascinante"
  },
  price: 31,
  dateStart: '07/02/2020',
  dateEnd: '11/02/2020',
  sign: '£',
  language: 'en',},
{ id: 47,
  url:'image/rio-m-01.jpg',
  city: 'Rio de Janeiro, RJ, Brasil',
  gender: 'male',
  description:  {
    pt: "Confortável e moderno",
    en: "Comfortable and modern",
    es: "Cómodo y moderno",
    it: "Confortevole e moderno"
  },
  price: 12,
  dateStart: '09/02/2020',
  dateEnd: '13/02/2020',
  sign: '£',
  language: 'en',},
{ id: 48,
  url:'image/rio-m-02.jpg',
  city: 'Rio de Janeiro, RJ, Brasil',
  gender: 'male',
   description:  {
    pt: "Estilo e elegancia",
    en: "Elegant and style",
    es: "Elegante y estilo",
    it: "Elegante e di stile"
  },
  price: 12,
  dateStart: '10/02/2020',
  dateEnd: '15/02/2020',
  sign: '£',
  language: 'en',},
/*-------São Paulo--------*/
{
  id: 49,
  url:'image/sao-c-01.jpg',
  city: 'São Paulo, SP, Brasil',
  gender: 'child',
  description:  {
    pt: "Roupas coloridas e unissex",
    en: "Colorfull and unissex clothes",
    es: "Ropa colorida y unissex",
    it: "Abiti colorati e unissex"
  },
  price: 18,
  dateStart: '12/02/2020',
  dateEnd: '18/02/2020',
  sign: '£',
  language: 'en',
  
},
{ id: 50,
  url:'image/sao-c-02.jpg',
  city: 'São Paulo, SP, Brasil',
  gender: 'child',
   description:  {
    pt: "Charme, delicadeza e diversão",
    en: "Charm, delicate and fun",
    es: "Encanto, delicado y divertido",
    it: "Fascino, delicato e divertente"
  },
  price: 23,
  dateStart: '14/02/2020',
  dateEnd: '20/02/2020',
  sign: '£',
  language: 'en'},
{ id: 51,
  url:'image/sao-c-03.jpg',
  city: 'São Paulo, SP, Brasil',
  gender: 'child',
  description:  {
    pt: "Artesanal. delicado e doce",
    en: "Handmade, delicate and sweet",
    es: "Hecho a mano, delicado y dulce",
    it: "Fatto a mano, delicato e dolce"
  },
  price: 6,
  dateStart: '16/02/2020',
  dateEnd: '22/02/2020',
  sign: '£',
  language: 'en'},
{ id: 52,
  url:'image/sao-f-01.jpg',
  city: 'São Paulo, SP, Brasil',
  gender: 'female',
  description:  {
    pt: "Charme, elegancia e conforto",
    en: "charm, fancy and comfortable",
    es: "encanto, elegante y confortable",
    it: "Affascinante, elegante e confortevole"
  },
  price: 42,
  dateStart: '18/02/2020',
  dateEnd: '24/02/2020',
  sign: '£',
  language: 'en'},
{ id: 53,
  url:'image/sao-f-02.jpg',
  city: 'São Paulo, SP, Brasil',
  gender: 'female',
  description:  {
    pt: "Moderno, artesanal e elegante",
    en: "Modern, handmade and elegant",
    es: "Moderno, artesanal y elegante",
    it: "Moderno, fatto a mano ed elegante"
  },
  price: 17,
  dateStart: '20/02/2020',
  dateEnd: '28/02/2020',
  sign: '£',
  language: 'en'},
{ id: 54,
  url:'image/sao-f-03.jpg',
  city: 'São Paulo, SP, Brasil',
  gender: 'female',
   description:  {
    pt: "Confortável, moderno e charmoso",
    en: "Comfortable, modern and charm",
    es: "Cómodo, moderno y con encanto",
    it: "Confortevole, moderno e affascinante"
  },
  price: 11,
  dateStart: '24/02/2020',
  dateEnd: '02/03/2020',
  sign: '£',
  language: 'en'},
{ id: 55,
  url:'image/rio-m-01.jpg',
  city: 'São Paulo, SP, Brasil',
  gender: 'male',
  description:  {
    pt: "Confortável e moderno",
    en: "Comfortable and modern",
    es: "Cómodo y moderno",
    it: "Confortevole e moderno"
  },
  price: 23,
  dateStart: '02/03/2020',
  dateEnd: '05/03/2020',
  sign: '£',
  language: 'en'},
{ id: 56,
  url:'image/rio-m-02.jpg',
  city: 'São Paulo, SP, Brasil',
  gender: 'male',
   description:  {
    pt: "Estilo e elegancia",
    en: "Elegant and style",
    es: "Elegante y estilo",
    it: "Elegante e di stile"
  },
  price: 7,
  dateStart: '04/03/2020',
  dateEnd: '08/03/2020',
  sign: '£',
  language: 'en'},

/*-------New York--------*/
{ id: 57,
  url:'image/new-c-01.jpg',
  city: 'New York, NY, EUA',
  gender: 'child',
  description:  {
    pt: "Roupas coloridas e unissex",
    en: "Colorfull and unissex clothes",
    es: "Ropa colorida y unissex",
    it: "Abiti colorati e unissex"
  },
  price: 8,
  dateStart: '06/03/2020',
  dateEnd: '10/03/2020',
  sign: '£',
  language: 'en'},
{ id: 58,
  url:'image/new-c-02.jpg',
  city: 'New York, NY, EUA',
  gender: 'child',
   description:  {
    pt: "Charme, delicadeza e diversão",
    en: "Charm, delicate and fun",
    es: "Encanto, delicado y divertido",
    it: "Fascino, delicato e divertente"
  },
  price: 12,
  dateStart: '08/03/2020',
  dateEnd: '12/03/2020',
  sign: '£',
  language: 'en'},

{
  id: 59,
  url:'image/new-c-03.jpg',
  city: 'New York, NY, EUA',
  gender: 'child',
  description:  {
    pt: "Artesanal. delicado e doce",
    en: "Handmade, delicate and sweet",
    es: "Hecho a mano, delicado y dulce",
    it: "Fatto a mano, delicato e dolce"
  },
  price: 21,
  dateStart: '10/03/2020',
  dateEnd: '12/03/2020',
  sign: '£',
  language: 'en',
  
},
{ id: 60,
  url:'image/new-f-01.jpg',
  city: 'New York, NY, EUA',
  gender: 'female',
  description:  {
    pt: "Charme, elegancia e conforto",
    en: "charm, fancy and comfortable",
    es: "encanto, elegante y confortable",
    it: "Affascinante, elegante e confortevole"
  },
  price: 27,
  dateStart: '12/03/2020',
  dateEnd: '14/03/2020',
  sign: '£',
  language: 'en'},
{ id: 61,
  url:'image/new-f-02.jpg',
  city: 'New York, NY, EUA',
  gender: 'female',
  description:  {
    pt: "Moderno, artesanal e elegante",
    en: "Modern, handmade and elegant",
    es: "Moderno, artesanal y elegante",
    it: "Moderno, fatto a mano ed elegante"
  },
  price: 70,
  dateStart: '13/03/2020',
  dateEnd: '18/03/2020',
  sign: '£',
  language: 'en'},
{ id: 62,
  url:'image/new-f-03.jpg',
  city: 'New York, NY, EUA',
  gender: 'female',
   description:  {
    pt: "Confortável, moderno e charmoso",
    en: "Comfortable, modern and charm",
    es: "Cómodo, moderno y con encanto",
    it: "Confortevole, moderno e affascinante"
  },
  price: 28,
  dateStart: '16/03/2020',
  dateEnd: '20/03/2020',
  sign: '£',
  language: 'en'},
{ id: 63,
  url:'image/new-m-01.jpg',
  city: 'New York, NY, EUA',
  gender: 'male',
  description:  {
    pt: "Confortável e moderno",
    en: "Comfortable and modern",
    es: "Cómodo y moderno",
    it: "Confortevole e moderno"
  },
  price: 18,
  dateStart: '18/03/2020',
  dateEnd: '23/03/2020',
  sign: '£',
  language: 'en'},
{ id: 64,
  url:'image/new-m-02.jpg',
  city: 'New York, NY, EUA',
  gender: 'male',
   description:  {
    pt: "Estilo e elegancia",
    en: "Elegant and style",
    es: "Elegante y estilo",
    it: "Elegante e di stile"
  },
  price: 25,
  dateStart: '20/03/2020',
  dateEnd: '27/03/2020',
  sign: '£',
  language: 'en'},

/*-------Bristol--------*/
{ id: 65,
  url:'image/bristol-c-01.jpg',
  city: 'Bristol, Reino Unido',
  gender: 'child',
  description:  {
    pt: "Roupas coloridas e unissex",
    en: "Colorfull and unissex clothes",
    es: "Ropa colorida y unissex",
    it: "Abiti colorati e unissex"
  },
  price: 16,
  dateStart: '24/03/2020',
  dateEnd: '30/03/2020',
  sign: '£',
  language: 'en'},
{ id: 66,
  url:'image/bristol-c-02.jpg',
  city: 'Bristol, Reino Unido',
  gender: 'child',
   description:  {
    pt: "Charme, delicadeza e diversão",
    en: "Charm, delicate and fun",
    es: "Encanto, delicado y divertido",
    it: "Fascino, delicato e divertente"
  },
  price: 9,
  dateStart: '02/04/2020',
  dateEnd: '05/04/2020',
  sign: '£',
  language: 'en'},
{ id: 67,
  url:'image/bristol-c-03.jpg',
  city: 'Bristol, Reino Unido',
  gender: 'child',
  description:  {
    pt: "Artesanal. delicado e doce",
    en: "Handmade, delicate and sweet",
    es: "Hecho a mano, delicado y dulce",
    it: "Fatto a mano, delicato e dolce"
  },
  price: 28,
  dateStart: '05/04/2020',
  dateEnd: '09/04/2020',
  sign: '£',
  language: 'en'},
{ id: 68,
  url:'image/bristol-f-01.jpg',
  city: 'Bristol, Reino Unido',
  gender: 'female',
  description:  {
    pt: "Charme, elegancia e conforto",
    en: "charm, fancy and comfortable",
    es: "encanto, elegante y confortable",
    it: "Affascinante, elegante e confortevole"
  },
  price: 13,
  dateStart: '07/04/2020',
  dateEnd: '11/04/2020',
  sign: '£',
  language: 'en'},
{ id: 69,
  url:'image/bristol-f-02.jpg',
  city: 'Bristol, Reino Unido',
  gender: 'female',
  description:  {
    pt: "Moderno, artesanal e elegante",
    en: "Modern, handmade and elegant",
    es: "Moderno, artesanal y elegante",
    it: "Moderno, fatto a mano ed elegante"
  },
  price: 38,
  dateStart: '09/04/2020',
  dateEnd: '13/04/2020',
  sign: '£',
  language: 'en'},
{ id: 70,
  url:'image/bristol-f-03.jpg',
  city: 'Bristol, Reino Unido',
  gender: 'female',
   description:  {
    pt: "Confortável, moderno e charmoso",
    en: "Comfortable, modern and charm",
    es: "Cómodo, moderno y con encanto",
    it: "Confortevole, moderno e affascinante"
  },
  price: 19,
  dateStart: '11/04/2020',
  dateEnd: '18/04/2020',
  sign: '£',
  language: 'en'},
{ id: 71,
  url:'image/f-01.jpg',
  city: 'Bristol, Reino Unido',
  gender: 'female',
   description:  {
    pt: "Confortável, moderno e charmoso",
    en: "Comfortable, modern and charm",
    es: "Cómodo, moderno y con encanto",
    it: "Confortevole, moderno e affascinante"
  },
  price: 22,
  dateStart: '13/04/2020',
  dateEnd: '18/04/2020',
  sign: '£',
  language: 'en'},
{ id: 72,
  url:'image/bristol-m-01.jpg',
  city: 'Bristol, Reino Unido',
  gender: 'male',
  description:  {
    pt: "Confortável e moderno",
    en: "Comfortable and modern",
    es: "Cómodo y moderno",
    it: "Confortevole e moderno"
  },
  price: 13,
  dateStart: '15/04/2020',
  dateEnd: '20/04/2020',
  sign: '£',
  language: 'en'},
{ id: 73,
  url:'image/bristol-m-02.jpg',
  city: 'Bristol, Reino Unido',
  gender: 'male',
   description:  {
    pt: "Estilo e elegancia",
    en: "Elegant and style",
    es: "Elegante y estilo",
    it: "Elegante e di stile"
  },
  price: 5,
  dateStart: '18/04/2020',
  dateEnd: '22/04/2020',
  sign: '£',
  language: 'en'},

/*-------Gloucester--------*/
{ id: 74,
  url:'image/gloucester-c-01.jpg',
  city: 'Gloucester, Reino Unido',
  gender: 'child',
  description:  {
    pt: "Roupas coloridas e unissex",
    en: "Colorfull and unissex clothes",
    es: "Ropa colorida y unissex",
    it: "Abiti colorati e unissex"
  },
  price: 15,
  dateStart: '20/04/2020',
  dateEnd: '24/04/2020',
  sign: '£',
  language: 'en'},
{ id: 75,
  url:'image/gloucester-c-02.jpg',
  city: 'Gloucester, Reino Unido',
  gender: 'child',
   description:  {
    pt: "Charme, delicadeza e diversão",
    en: "Charm, delicate and fun",
    es: "Encanto, delicado y divertido",
    it: "Fascino, delicato e divertente"
  },
  price: 22,
  dateStart: '22/04/2020',
  dateEnd: '27/04/2020',
  sign: '£',
  language: 'en'},
{ id: 76,
  url:'image/gloucester-c-03.jpg',
  city: 'Gloucester, Reino Unido',
  gender: 'child',
  description:  {
    pt: "Artesanal. delicado e doce",
    en: "Handmade, delicate and sweet",
    es: "Hecho a mano, delicado y dulce",
    it: "Fatto a mano, delicato e dolce"
  },
  price: 11,
  dateStart: '24/04/2020',
  dateEnd: '30/04/2020',
  sign: '£',
  language: 'en'},
{ id: 77,
  url:'image/gloucester-f-01.jpg',
  city: 'Gloucester, Reino Unido',
  gender: 'female',
  description:  {
    pt: "Charme, elegancia e conforto",
    en: "charm, fancy and comfortable",
    es: "encanto, elegante y confortable",
    it: "Affascinante, elegante e confortevole"
  },
  price: 15,
  dateStart: '28/04/2020',
  dateEnd: '02/05/2020',
  sign: '£',
  language: 'en'},
{ id: 78,
  url:'image/gloucester-f-02.jpg',
  city: 'Gloucester, Reino Unido',
  gender: 'female',
  description:  {
    pt: "Moderno, artesanal e elegante",
    en: "Modern, handmade and elegant",
    es: "Moderno, artesanal y elegante",
    it: "Moderno, fatto a mano ed elegante"
  },
  price: 11,
  dateStart: '03/05/2020',
  dateEnd: '05/05/2020',
  sign: '£',
  language: 'en'},
{ id: 79,
  url:'image/f-02.jpg',
  city: 'Gloucester, Reino Unido',
  gender: 'female',
   description:  {
    pt: "Confortável, moderno e charmoso",
    en: "Comfortable, modern and charm",
    es: "Cómodo, moderno y con encanto",
    it: "Confortevole, moderno e affascinante"
  },
  price: 25,
  dateStart: '05/05/2020',
  dateEnd: '08/05/2020',
  sign: '£',
  language: 'en'},
{ id: 80,
  url:'image/gloucester-m-01.jpg',
  city: 'Gloucester, Reino Unido',
  gender: 'male',
  description:  {
    pt: "Confortável e moderno",
    en: "Comfortable and modern",
    es: "Cómodo y moderno",
    it: "Confortevole e moderno"
  },
  price: 18,
  dateStart: '07/05/2020',
  dateEnd: '10/05/2020',
  sign: '£',
  language: 'en'},
{ id: 81,
  url:'image/gloucester-m-02.jpg',
  city: 'Gloucester, Reino Unido',
  gender: 'male',
   description:  {
    pt: "Estilo e elegancia",
    en: "Elegant and style",
    es: "Elegante y estilo",
    it: "Elegante e di stile"
  },
  price: 28,
  dateStart: '09/05/2020',
  dateEnd: '11/05/2020',
  sign: '£',
  language: 'en'},

/*-------Manchester--------*/

{ id: 82,
  url:'image/manchester-c-01.jpg',
  city: 'Manchester, Reino Unido',
  gender: 'child',
  description:  {
    pt: "Roupas coloridas e unissex",
    en: "Colorfull and unissex clothes",
    es: "Ropa colorida y unissex",
    it: "Abiti colorati e unissex"
  },
  price: 8,
  dateStart: '11/05/2020',
  dateEnd: '13/05/2020',
  sign: '£',
  language: 'en'},
{ id: 83,
  url:'image/manchester-c-02.jpg',
  city: 'Manchester, Reino Unido',
  gender: 'child',
   description:  {
    pt: "Charme, delicadeza e diversão",
    en: "Charm, delicate and fun",
    es: "Encanto, delicado y divertido",
    it: "Fascino, delicato e divertente"
  },
  price: 31,
  dateStart: '13/05/2020',
  dateEnd: '16/05/2020',
  sign: '£',
  language: 'en'},
{ id: 84,
  url:'image/manchester-c-03.jpg',
  city: 'Manchester, Reino Unido',
  gender: 'child',
  description:  {
    pt: "Artesanal. delicado e doce",
    en: "Handmade, delicate and sweet",
    es: "Hecho a mano, delicado y dulce",
    it: "Fatto a mano, delicato e dolce"
  },
  price: 12,
  dateStart: '15/05/2020',
  dateEnd: '18/05/2020',
  sign: '£',
  language: 'en'},
{ id: 85,
  url:'image/manchester-f-01.jpg',
  city: 'Manchester, Reino Unido',
  gender: 'female',
  description:  {
    pt: "Charme, elegancia e conforto",
    en: "charm, fancy and comfortable",
    es: "encanto, elegante y confortable",
    it: "Affascinante, elegante e confortevole"
  },
  price: 14,
  dateStart: '17/05/2020',
  dateEnd: '20/05/2020',
  sign: '£',
  language: 'en'},
{ id: 86,
  url:'image/manchester-f-02.jpg',
  city: 'Manchester, Reino Unido',
  gender: 'female',
  description:  {
    pt: "Moderno, artesanal e elegante",
    en: "Modern, handmade and elegant",
    es: "Moderno, artesanal y elegante",
    it: "Moderno, fatto a mano ed elegante"
  },
  price: 21,
  dateStart: '19/05/2020',
  dateEnd: '22/05/2020',
  sign: '£',
  language: 'en'},
{ id: 87,
  url:'image/manchester-f-03.jpg',
  city: 'Manchester, Reino Unido',
  gender: 'female',
   description:  {
    pt: "Confortável, moderno e charmoso",
    en: "Comfortable, modern and charm",
    es: "Cómodo, moderno y con encanto",
    it: "Confortevole, moderno e affascinante"
  },
  price: 38,
  dateStart: '21/05/2020',
  dateEnd: '23/05/2020',
  sign: '£',
  language: 'en'},
{ id: 88,
  url:'image/manchester-m-01.jpg',
  city: 'Manchester, Reino Unido',
  gender: 'male',
  description:  {
    pt: "Confortável e moderno",
    en: "Comfortable and modern",
    es: "Cómodo y moderno",
    it: "Confortevole e moderno"
  },
  price: 6,
  dateStart: '23/05/2020',
  dateEnd: '27/05/2020',
  sign: '£',
  language: 'en'},
{ id: 89,
  url:'image/manchester-m-02.jpg',
  city: 'Manchester, Reino Unido',
  gender: 'male',
   description:  {
    pt: "Estilo e elegancia",
    en: "Elegant and style",
    es: "Elegante y estilo",
    it: "Elegante e di stile"
  },
  price: 14,
  dateStart: '25/05/2020',
  dateEnd: '30/05/2020',
  sign: '£',
  language: 'en'},

/*-------Liverpool--------*/
{ id: 90,
  url:'image/liverpool-c-01.jpg',
  city: 'Liverpool, Reino Unido',
  gender: 'child',
  description:  {
    pt: "Roupas coloridas e unissex",
    en: "Colorfull and unissex clothes",
    es: "Ropa colorida y unissex",
    it: "Abiti colorati e unissex"
  },
  price: 8,
  dateStart: '01/06/2020',
  dateEnd: '04/06/2020',
  sign: '£',
  language: 'en'},
{ id: 91,
  url:'image/liverpool-c-02.jpg',
  city: 'Liverpool, Reino Unido',
  gender: 'child',
   description:  {
    pt: "Charme, delicadeza e diversão",
    en: "Charm, delicate and fun",
    es: "Encanto, delicado y divertido",
    it: "Fascino, delicato e divertente"
  },
  price: 21,
  dateStart: '03/06/2020',
  dateEnd: '07/06/2020',
  sign: '£',
  language: 'en'},
{ id: 92,
  url:'image/liverpool-c-03.jpg',
  city: 'Liverpool, Reino Unido',
  gender: 'child',
  description:  {
    pt: "Artesanal. delicado e doce",
    en: "Handmade, delicate and sweet",
    es: "Hecho a mano, delicado y dulce",
    it: "Fatto a mano, delicato e dolce"
  },
  price: 12,
  dateStart: '05/06/2020',
  dateEnd: '08/06/2020',
  sign: '£',
  language: 'en'},
{ id: 93,
  url:'image/liverpool-f-01.jpg',
  city: 'Liverpool, Reino Unido',
  gender: 'female',
  description:  {
    pt: "Charme, elegancia e conforto",
    en: "charm, fancy and comfortable",
    es: "encanto, elegante y confortable",
    it: "Affascinante, elegante e confortevole"
  },
  price: 19,
  dateStart: '07/06/2020',
  dateEnd: '10/06/2020',
  sign: '£',
  language: 'en'},
{ id: 94,
  url:'image/liverpool-f-02.jpg',
  city: 'Liverpool, Reino Unido',
  gender: 'female',
  description:  {
    pt: "Moderno, artesanal e elegante",
    en: "Modern, handmade and elegant",
    es: "Moderno, artesanal y elegante",
    it: "Moderno, fatto a mano ed elegante"
  },
  price: 21,
  dateStart: '09/06/2020',
  dateEnd: '12/06/2020',
  sign: '£',
  language: 'en'},
{ id: 95,
  url:'image/liverpool-f-03.jpg',
  city: 'Liverpool, Reino Unido',
  gender: 'female',
   description:  {
    pt: "Confortável, moderno e charmoso",
    en: "Comfortable, modern and charm",
    es: "Cómodo, moderno y con encanto",
    it: "Confortevole, moderno e affascinante"
  },
  price: 51,
  dateStart: '11/06/2020',
  dateEnd: '14/06/2020',
  sign: '£',
  language: 'en'},
{ id: 96,
  url:'image/liverpool-m-01.jpg',
  city: 'Liverpool, Reino Unido',
  gender: 'male',
  description:  {
    pt: "Confortável e moderno",
    en: "Comfortable and modern",
    es: "Cómodo y moderno",
    it: "Confortevole e moderno"
  },
  price: 7,
  dateStart: '13/06/2020',
  dateEnd: '18/06/2020',
  sign: '£',
  language: 'en'},
{ id: 97,
  url:'image/liverpool-m-02.jpg',
  city: 'Liverpool, Reino Unido',
  gender: 'male',
   description:  {
    pt: "Estilo e elegancia",
    en: "Elegant and style",
    es: "Elegante y estilo",
    it: "Elegante e di stile"
  },
  price: 19,
  dateStart: '16/06/2020',
  dateEnd: '18/06/2020',
  sign: '£',
  language: 'en'},

/*-------Endingurg--------*/
{ id: 98,
  url:'image/edinburg-c-01.jpg',
  city: 'Edinburgh, Reino Unido',
  gender: 'child',
  description:  {
    pt: "Roupas coloridas e unissex",
    en: "Colorfull and unissex clothes",
    es: "Ropa colorida y unissex",
    it: "Abiti colorati e unissex"
  },
  price: 8,
  dateStart: '18/06/2020',
  dateEnd: '22/06/2020',
  sign: '£',
  language: 'en'},
{ id: 99,
  url:'image/edinburg-c-02.jpg',
  city: 'Edinburgh, Reino Unido',
  gender: 'child',
   description:  {
    pt: "Charme, delicadeza e diversão",
    en: "Charm, delicate and fun",
    es: "Encanto, delicado y divertido",
    it: "Fascino, delicato e divertente"
  },
  price: 12,
  dateStart: '20/06/2020',
  dateEnd: '25/06/2020',
  sign: '£',
  language: 'en'},
{ id: 100,
  url:'image/edinburg-c-03.jpg',
  city: 'Edinburgh, Reino Unido',
  gender: 'child',
  description:  {
    pt: "Artesanal. delicado e doce",
    en: "Handmade, delicate and sweet",
    es: "Hecho a mano, delicado y dulce",
    it: "Fatto a mano, delicato e dolce"
  },
  price: 17,
  dateStart: '23/06/2020',
  dateEnd: '25/06/2020',
  sign: '£',
  language: 'en'},
{ id: 101,
  url:'image/edinburg-f-01.jpg',
  city: 'Edinburgh, Reino Unido',
  gender: 'female',
  description:  {
    pt: "Charme, elegancia e conforto",
    en: "charm, fancy and comfortable",
    es: "encanto, elegante y confortable",
    it: "Affascinante, elegante e confortevole"
  },
  price: 36,
  dateStart: '25/06/2020',
  dateEnd: '27/06/2020',
  sign: '£',
  language: 'en'},
{ id: 102,
  url:'image/edinburg-f-02.jpg',
  city: 'Edinburgh, Reino Unido',
  gender: 'female',
  description:  {
    pt: "Moderno, artesanal e elegante",
    en: "Modern, handmade and elegant",
    es: "Moderno, artesanal y elegante",
    it: "Moderno, fatto a mano ed elegante"
  },
  price: 89,
  dateStart: '27/06/2020',
  dateEnd: '30/06/2020',
  sign: '£',
  language: 'en'},
{ id: 103,
  url:'image/edinburg-f-03.jpg',
  city: 'Edinburgh, Reino Unido',
  gender: 'female',
   description:  {
    pt: "Confortável, moderno e charmoso",
    en: "Comfortable, modern and charm",
    es: "Cómodo, moderno y con encanto",
    it: "Confortevole, moderno e affascinante"
  },
  price: 7,
  dateStart: '29/06/2020',
  dateEnd: '03/07/2020',
  sign: '£',
  language: 'en'},
{ id: 104,
  url:'image/edinburg-m-01.jpg',
  city: 'Edinburgh, Reino Unido',
  gender: 'male',
  description:  {
    pt: "Confortável e moderno",
    en: "Comfortable and modern",
    es: "Cómodo y moderno",
    it: "Confortevole e moderno"
  },
  price: 12,
  dateStart: '04/07/2020',
  dateEnd: '06/07/2020',
  sign: '£',
  language: 'en'},
{ id: 105,
  url:'image/edinburg-m-02.jpg',
  city: 'Edinburgh, Reino Unido',
  gender: 'male',
   description:  {
    pt: "Estilo e elegancia",
    en: "Elegant and style",
    es: "Elegante y estilo",
    it: "Elegante e di stile"
  },
  price: 34,
  dateStart: '07/07/2020',
  dateEnd: '09/07/2020',
  sign: '£',
  language: 'en'},

/*-------Dublin--------*/
{ id: 106,
  url:'image/dublin-c-01.jpg',
  city: 'Dublin, Irlanda',
  gender: 'child',
  description:  {
    pt: "Roupas coloridas e unissex",
    en: "Colorfull and unissex clothes",
    es: "Ropa colorida y unissex",
    it: "Abiti colorati e unissex"
  },
  price: 18,
  dateStart: '09/07/2020',
  dateEnd: '11/07/2020',
  sign: '£',
  language: 'en'},
{ id: 107,
  url:'image/dublin-c-02.jpg',
  city: 'Dublin, Irlanda',
  gender: 'child',
   description:  {
    pt: "Charme, delicadeza e diversão",
    en: "Charm, delicate and fun",
    es: "Encanto, delicado y divertido",
    it: "Fascino, delicato e divertente"
  },
  price: 6,
  dateStart: '10/07/2020',
  dateEnd: '14/07/2020',
  sign: '£',
  language: 'en'},
{ id: 108,
  url:'image/dublin-c-03.jpg',
  city: 'Dublin, Irlanda',
  gender: 'child',
  description:  {
    pt: "Artesanal. delicado e doce",
    en: "Handmade, delicate and sweet",
    es: "Hecho a mano, delicado y dulce",
    it: "Fatto a mano, delicato e dolce"
  },
  price: 23,
  dateStart: '12/07/2020',
  dateEnd: '14/07/2020',
  sign: '£',
  language: 'en'},
{ id: 109,
  url:'image/dublin-f-01.jpg',
  city: 'Dublin, Irlanda',
  gender: 'female',
  description:  {
    pt: "Charme, elegancia e conforto",
    en: "charm, fancy and comfortable",
    es: "encanto, elegante y confortable",
    it: "Affascinante, elegante e confortevole"
  },
  price: 26,
  dateStart: '09/07/2020',
  dateEnd: '11/07/2020',
  sign: '£',
  language: 'en'},
{ id: 110,
  url:'image/dublin-f-02.jpg',
  city: 'Dublin, Irlanda',
  gender: 'female',
  description:  {
    pt: "Moderno, artesanal e elegante",
    en: "Modern, handmade and elegant",
    es: "Moderno, artesanal y elegante",
    it: "Moderno, fatto a mano ed elegante"
  },
  price: 11,
  dateStart: '09/07/2020',
  dateEnd: '15/07/2020',
  sign: '£',
  language: 'en'},
{ id: 111,
  url:'image/dublin-f-03.jpg',
  city: 'Dublin, Irlanda',
  gender: 'female',
   description:  {
    pt: "Confortável, moderno e charmoso",
    en: "Comfortable, modern and charm",
    es: "Cómodo, moderno y con encanto",
    it: "Confortevole, moderno e affascinante"
  },
  price: 89,
  dateStart: '13/07/2020',
  dateEnd: '17/07/2020',
  sign: '£',
  language: 'en'},
{ id: 112,
  url:'image/dublin-m-01.jpg',
  city: 'Dublin, Irlanda',
  gender: 'male',
  description:  {
    pt: "Confortável e moderno",
    en: "Comfortable and modern",
    es: "Cómodo y moderno",
    it: "Confortevole e moderno"
  },
  price: 15,
  dateStart: '17/07/2020',
  dateEnd: '19/07/2020',
  sign: '£',
  language: 'en'},
{ id: 113,
  url:'image/dublin-m-02.jpg',
  city: 'Dublin, Irlanda',
  gender: 'male',
  description:  {
    pt: "Estilo e elegancia",
    en: "Elegant and style",
    es: "Elegante y estilo",
    it: "Elegante e di stile"
  },
  price: 23,
  dateStart: '18/07/2020',
  dateEnd: '23/07/2020',
  sign: '£',
  language: 'en'},

/*-------Miami--------*/
{ id: 114,
  url:'image/miami-c-01.jpg',
  city: 'Miami, Flórida, EUA',
  gender: 'child',
  description:  {
    pt: "Roupas coloridas e unissex",
    en: "Colorfull and unissex clothes",
    es: "Ropa colorida y unissex",
    it: "Abiti colorati e unissex"
  },
  price: 13,
  dateStart: '20/07/2020',
  dateEnd: '23/07/2020',
  sign: '£',
  language: 'en'},
{ id: 115,
  url:'image/miami-c-02.jpg',
  city: 'Miami, Flórida, EUA',
  gender: 'child',
   description:  {
    pt: "Charme, delicadeza e diversão",
    en: "Charm, delicate and fun",
    es: "Encanto, delicado y divertido",
    it: "Fascino, delicato e divertente"
  },
  price: 21,
  dateStart: '22/07/2020',
  dateEnd: '25/07/2020',
  sign: '£',
  language: 'en'},
{ id: 116,
  url:'image/miami-c-03.jpg',
  city: 'Miami, Flórida, EUA',
  gender: 'child',
  description:  {
    pt: "Artesanal. delicado e doce",
    en: "Handmade, delicate and sweet",
    es: "Hecho a mano, delicado y dulce",
    it: "Fatto a mano, delicato e dolce"
  },
  price: 34,
  dateStart: '21/07/2020',
  dateEnd: '23/07/2020',
  sign: '£',
  language: 'en'},
{ id: 117,
  url:'image/miami-f-01.jpg',
  city: 'Miami, Flórida, EUA',
  gender: 'female',
  description:  {
    pt: "Charme, elegancia e conforto",
    en: "charm, fancy and comfortable",
    es: "encanto, elegante y confortable",
    it: "Affascinante, elegante e confortevole"
  },
  price: 13,
  dateStart: '23/07/2020',
  dateEnd: '25/07/2020',
  sign: '£',
  language: 'en'},
{ id: 118,
  url:'image/miami-f-02.jpg',
  city: 'Miami, Flórida, EUA',
  gender: 'female',
  description:  {
    pt: "Moderno, artesanal e elegante",
    en: "Modern, handmade and elegant",
    es: "Moderno, artesanal y elegante",
    it: "Moderno, fatto a mano ed elegante"
  },
  price: 33,
  dateStart: '22/07/2020',
  dateEnd: '27/07/2020',
  sign: '£',
  language: 'en'},
{ id: 119,
  url:'image/miami-f-03.jpg',
  city: 'Miami, Flórida, EUA',
  gender: 'female',
   description:  {
    pt: "Confortável, moderno e charmoso",
    en: "Comfortable, modern and charm",
    es: "Cómodo, moderno y con encanto",
    it: "Confortevole, moderno e affascinante"
  },
  price: 44,
  dateStart: '20/07/2020',
  dateEnd: '23/07/2020',
  sign: '£',
  language: 'en'},
{ id: 120,
  url:'image/miami-m-01.jpg',
  city: 'Miami, Flórida, EUA',
  gender: 'male',
  description:  {
    pt: "Confortável e moderno",
    en: "Comfortable and modern",
    es: "Cómodo y moderno",
    it: "Confortevole e moderno"
  },
  price: 17,
  dateStart: '24/07/2020',
  dateEnd: '27/07/2020',
  sign: '£',
  language: 'en'},
{ id: 121,
  url:'image/miami-m-02.jpg',
  city: 'Miami, Flórida, EUA',
  gender: 'male',
  description:  {
    pt: "Estilo e elegancia",
    en: "Elegant and style",
    es: "Elegante y estilo",
    it: "Elegante e di stile"
  },
  price: 10,
  dateStart: '27/07/2020',
  dateEnd: '29/07/2020',
  sign: '£',
  language: 'en'},

/*-------Milão--------*/
{ id: 122,
  url:'image/milan-c-01.jpg',
  city: 'Milano, Milão, Itália',
  gender: 'child',
  description:  {
    pt: "Roupas coloridas e unissex",
    en: "Colorfull and unissex clothes",
    es: "Ropa colorida y unissex",
    it: "Abiti colorati e unissex"
  },
  price: 12,
  dateStart: '01/08/2020',
  dateEnd: '03/08/2020',
  sign: '£',
  language: 'en'},
{ id: 123,
  url:'image/milan-c-02.jpg',
  city: 'Milano, Milão, Itália',
  gender: 'child',
   description:  {
    pt: "Charme, delicadeza e diversão",
    en: "Charm, delicate and fun",
    es: "Encanto, delicado y divertido",
    it: "Fascino, delicato e divertente"
  },
  price: 21,
  dateStart: '02/08/2020',
  dateEnd: '07/08/2020',
  sign: '£',
  language: 'en'},
{ id: 124,
  url:'image/milan-c-03.jpg',
  city: 'Milano, Milão, Itália',
  gender: 'child',
  description:  {
    pt: "Artesanal. delicado e doce",
    en: "Handmade, delicate and sweet",
    es: "Hecho a mano, delicado y dulce",
    it: "Fatto a mano, delicato e dolce"
  },
  price: 6,
  dateStart: '10/08/2020',
  dateEnd: '15/08/2020',
  sign: '£',
  language: 'en'},
{ id: 125,
  url:'image/milan-f-01.jpg',
  city: 'Milano, Milão, Itália',
  gender: 'female',
  description:  {
    pt: "Charme, elegancia e conforto",
    en: "charm, fancy and comfortable",
    es: "encanto, elegante y confortable",
    it: "Affascinante, elegante e confortevole"
  },
  price: 32,
  dateStart: '05/08/2020',
  dateEnd: '09/08/2020',
  sign: '£',
  language: 'en'},
{ id: 126,
  url:'image/milan-f-02.jpg',
  city: 'Milano, Milão, Itália',
  gender: 'female',
  description:  {
    pt: "Moderno, artesanal e elegante",
    en: "Modern, handmade and elegant",
    es: "Moderno, artesanal y elegante",
    it: "Moderno, fatto a mano ed elegante"
  },
  price: 14,
  dateStart: '07/08/2020',
  dateEnd: '09/08/2020',
  sign: '£',
  language: 'en'},
{ id: 127,
  url:'image/milan-f-03.jpg',
  city: 'Milano, Milão, Itália',
  gender: 'female',
   description:  {
    pt: "Confortável, moderno e charmoso",
    en: "Comfortable, modern and charm",
    es: "Cómodo, moderno y con encanto",
    it: "Confortevole, moderno e affascinante"
  },
  price: 18,
  dateStart: '14/08/2020',
  dateEnd: '20/08/2020',
  sign: '£',
  language: 'en'},
{ id: 128,
  url:'image/milan-m-01.jpg',
  city: 'Milano, Milão, Itália',
  gender: 'male',
  description:  {
    pt: "Confortável e moderno",
    en: "Comfortable and modern",
    es: "Cómodo y moderno",
    it: "Confortevole e moderno"
  },
  price: 15,
  dateStart: '06/08/2020',
  dateEnd: '10/08/2020',
  sign: '£',
  language: 'en'},
{ id: 129,
  url:'image/milan-m-02.jpg',
  city: 'Milano, Milão, Itália',
  gender: 'male',
  description:  {
    pt: "Estilo e elegancia",
    en: "Elegant and style",
    es: "Elegante y estilo",
    it: "Elegante e di stile"
  },
  price: 40,
  dateStart: '08/07/2020',
  dateEnd: '13/07/2020',
  sign: '£',
  language: 'en'},

/*-------Roma--------*/
{ id: 130,
  url:'image/roma-c-01.jpg',
  city: 'Roma, Itália',
  gender: 'child',
  description:  {
    pt: "Roupas coloridas e unissex",
    en: "Colorfull and unissex clothes",
    es: "Ropa colorida y unissex",
    it: "Abiti colorati e unissex"
  },
  price: 13,
  dateStart: '09/08/2020',
  dateEnd: '12/08/2020',
  sign: '£',
  language: 'en'},
{ id: 131,
  url:'image/roma-c-02.jpg',
  city: 'Roma, Itália',
  gender: 'child',
   description:  {
    pt: "Charme, delicadeza e diversão",
    en: "Charm, delicate and fun",
    es: "Encanto, delicado y divertido",
    it: "Fascino, delicato e divertente"
  },
  price: 28,
  dateStart: '11/08/2020',
  dateEnd: '24/08/2020',
  sign: '£',
  language: 'en'},
{ id: 132,
  url:'image/roma-c-03.jpg',
  city: 'Roma, Itália',
  gender: 'child',
  description:  {
    pt: "Artesanal. delicado e doce",
    en: "Handmade, delicate and sweet",
    es: "Hecho a mano, delicado y dulce",
    it: "Fatto a mano, delicato e dolce"
  },
  price: 9,
  dateStart: '15/08/2020',
  dateEnd: '27/08/2020',
  sign: '£',
  language: 'en'},
{ id: 133,
  url:'image/roma-f-01.jpg',
  city: 'Roma, Itália',
  gender: 'female',
  description:  {
    pt: "Charme, elegancia e conforto",
    en: "charm, fancy and comfortable",
    es: "encanto, elegante y confortable",
    it: "Affascinante, elegante e confortevole"
  },
  price: 23,
  dateStart: '18/08/2020',
  dateEnd: '20/08/2020',
  sign: '£',
  language: 'en'},
{ id: 134,
  url:'image/roma-f-02.jpg',
  city: 'Roma, Itália',
  gender: 'female',
  description:  {
    pt: "Moderno, artesanal e elegante",
    en: "Modern, handmade and elegant",
    es: "Moderno, artesanal y elegante",
    it: "Moderno, fatto a mano ed elegante"
  },
  price: 17,
  dateStart: '21/08/2020',
  dateEnd: '26/08/2020',
  sign: '£',
  language: 'en'},
{ id: 135,
  url:'image/roma-f-03.jpg',
  city: 'Roma, Itália',
  gender: 'female',
   description:  {
    pt: "Confortável, moderno e charmoso",
    en: "Comfortable, modern and charm",
    es: "Cómodo, moderno y con encanto",
    it: "Confortevole, moderno e affascinante"
  },
  price: 90,
  dateStart: '23/08/2020',
  dateEnd: '27/08/2020',
  sign: '£',
  language: 'en'},
{ id: 136,
  url:'image/roma-m-01.jpg',
  city: 'Roma, Itália',
  gender: 'male',
  description:  {
    pt: "Confortável e moderno",
    en: "Comfortable and modern",
    es: "Cómodo y moderno",
    it: "Confortevole e moderno"
  },
  price: 19,
  dateStart: '27/08/2020',
  dateEnd: '29/08/2020',
  sign: '£',
  language: 'en'},
{ id: 137,
  url:'image/roma-m-02.jpg',
  city: 'Roma, Itália',
  gender: 'male',
  description:  {
    pt: "Estilo e elegancia",
    en: "Elegant and style",
    es: "Elegante y estilo",
    it: "Elegante e di stile"
  },
  price: 32,
  dateStart: '23/08/2020',
  dateEnd: '27/08/2020',
  sign: '£',
  language: 'en'},
/*-------Tokyo--------*/
{ id: 138,
  url:'image/tokyo-c-01.jpg',
  city: 'Tōkyō, Tóquio, Japão',
  gender: 'child',
  description:  {
    pt: "Roupas coloridas e unissex",
    en: "Colorfull and unissex clothes",
    es: "Ropa colorida y unissex",
    it: "Abiti colorati e unissex"
  },
  price: 11,
  dateStart: '01/09/2020',
  dateEnd: '04/09/2020',
  sign: '£',
  language: 'en'},
{ id: 139,
  url:'image/tokyo-c-02.jpg',
  city: 'Tōkyō, Tóquio, Japão',
  gender: 'child',
   description:  {
    pt: "Charme, delicadeza e diversão",
    en: "Charm, delicate and fun",
    es: "Encanto, delicado y divertido",
    it: "Fascino, delicato e divertente"
  },
  price: 23,
  dateStart: '03/09/2020',
  dateEnd: '08/09/2020',
  sign: '£',
  language: 'en'},
{ id: 140,
  url:'image/tokyo-c-03.jpg',
  city: 'Tōkyō, Tóquio, Japão',
  gender: 'child',
  description:  {
    pt: "Artesanal. delicado e doce",
    en: "Handmade, delicate and sweet",
    es: "Hecho a mano, delicado y dulce",
    it: "Fatto a mano, delicato e dolce"
  },
  price: 53,
  dateStart: '06/09/2020',
  dateEnd: '09/09/2020',
  sign: '£',
  language: 'en'},
{ id: 141,
  url:'image/tokyo-f-01.jpg',
  city: 'Tōkyō, Tóquio, Japão',
  gender: 'female',
  description:  {
    pt: "Charme, elegancia e conforto",
    en: "charm, fancy and comfortable",
    es: "encanto, elegante y confortable",
    it: "Affascinante, elegante e confortevole"
  },
  price: 17,
  dateStart: '08/09/2020',
  dateEnd: '11/09/2020',
  sign: '£',
  language: 'en'},
{ id: 142,
  url:'image/tokyo-f-02.jpg',
  city: 'Tōkyō, Tóquio, Japão',
  gender: 'female',
  description:  {
    pt: "Moderno, artesanal e elegante",
    en: "Modern, handmade and elegant",
    es: "Moderno, artesanal y elegante",
    it: "Moderno, fatto a mano ed elegante"
  },
  price: 76,
  dateStart: '13/09/2020',
  dateEnd: '17/09/2020',
  sign: '£',
  language: 'en'},
{ id: 143,
  url:'image/tokyo-f-03.jpg',
  city: 'Tōkyō, Tóquio, Japão',
  gender: 'female',
   description:  {
    pt: "Confortável, moderno e charmoso",
    en: "Comfortable, modern and charm",
    es: "Cómodo, moderno y con encanto",
    it: "Confortevole, moderno e affascinante"
  },
  price: 21,
  dateStart: '18/09/2020',
  dateEnd: '22/09/2020',
  sign: '£',
  language: 'en'},
{ id: 144,
  url:'image/tokyo-m-01.jpg',
  city: 'Tōkyō, Tóquio, Japão',
  gender: 'male',
  description:  {
    pt: "Confortável e moderno",
    en: "Comfortable and modern",
    es: "Cómodo y moderno",
    it: "Confortevole e moderno"
  },
  price: 9,
  dateStart: '12/09/2020',
  dateEnd: '23/09/2020',
  sign: '£',
  language: 'en'},
{ id: 145,
  url:'image/tokyo-m-02.jpg',
  city: 'Tōkyō, Tóquio, Japão',
  gender: 'male',
  description:  {
    pt: "Estilo e elegancia",
    en: "Elegant and style",
    es: "Elegante y estilo",
    it: "Elegante e di stile"
  },
  price: 36,
  dateStart: '08/08/2020',
  dateEnd: '11/08/2020',
  sign: '£',
  language: 'en'},
/*-------Berlin--------*/
{ id: 146,
  url:'image/verlin-c-01.jpg',
  city: 'Berlin, Alemanha',
  gender: 'child',
  description:  {
    pt: "Roupas coloridas e unissex",
    en: "Colorfull and unissex clothes",
    es: "Ropa colorida y unissex",
    it: "Abiti colorati e unissex"
  },
  price: 17,
  dateStart: '02/09/2020',
  dateEnd: '07/09/2020',
  sign: '£',
  language: 'en'},
{ id: 147,
  url:'image/verlin-c-02.jpg',
  city: 'Berlin, Alemanha',
  gender: 'child',
   description:  {
    pt: "Charme, delicadeza e diversão",
    en: "Charm, delicate and fun",
    es: "Encanto, delicado y divertido",
    it: "Fascino, delicato e divertente"
  },
  price: 11,
  dateStart: '05/09/2020',
  dateEnd: '09/09/2020',
  sign: '£',
  language: 'en'},
{ id: 148,
  url:'image/verlin-c-03.jpg',
  city: 'Berlin, Alemanha',
  gender: 'child',
  description:  {
    pt: "Artesanal. delicado e doce",
    en: "Handmade, delicate and sweet",
    es: "Hecho a mano, delicado y dulce",
    it: "Fatto a mano, delicato e dolce"
  },
  price: 47,
  dateStart: '07/09/2020',
  dateEnd: '11/09/2020',
  sign: '£',
  language: 'en'},
{ id: 149,
  url:'image/verlin-f-01.jpg',
  city: 'Berlin, Alemanha',
  gender: 'female',
  description:  {
    pt: "Charme, elegancia e conforto",
    en: "charm, fancy and comfortable",
    es: "encanto, elegante y confortable",
    it: "Affascinante, elegante e confortevole"
  },
  price: 12,
  dateStart: '10/09/2020',
  dateEnd: '13/09/2020',
  sign: '£',
  language: 'en'},
{ id: 150,
  url:'image/verlin-f-02.jpg',
  city: 'Berlin, Alemanha',
  gender: 'female',
  description:  {
    pt: "Moderno, artesanal e elegante",
    en: "Modern, handmade and elegant",
    es: "Moderno, artesanal y elegante",
    it: "Moderno, fatto a mano ed elegante"
  },
  price: 36,
  dateStart: '11/09/2020',
  dateEnd: '17/09/2020',
  sign: '£',
  language: 'en'},
{ id: 151,
  url:'image/verlin-f-03.jpg',
  city: 'Berlin, Alemanha',
  gender: 'female',
   description:  {
    pt: "Confortável, moderno e charmoso",
    en: "Comfortable, modern and charm",
    es: "Cómodo, moderno y con encanto",
    it: "Confortevole, moderno e affascinante"
  },
  price: 7,
  dateStart: '15/09/2020',
  dateEnd: '17/09/2020',
  sign: '£',
  language: 'en'},
{ id: 152,
  url:'image/verlin-m-01.jpg',
  city: 'Berlin, Alemanha',
  gender: 'male',
  description:  {
    pt: "Confortável e moderno",
    en: "Comfortable and modern",
    es: "Cómodo y moderno",
    it: "Confortevole e moderno"
  },
  price: 15,
  dateStart: '21/09/2020',
  dateEnd: '27/09/2020',
  sign: '£',
  language: 'en'},
{ id: 153,
  url:'image/verlin-m-02.jpg',
  city: 'Berlin, Alemanha',
  gender: 'male',
  description:  {
    pt: "Estilo e elegancia",
    en: "Elegant and style",
    es: "Elegante y estilo",
    it: "Elegante e di stile"
  },
  price: 29,
  dateStart: '25/08/2020',
  dateEnd: '29/08/2020',
  sign: '£',
  language: 'en'},
/*-------Munique--------*/
{ id: 154,
  url:'image/munique-c-01.jpg',
  city: 'Munich, Alemanha',
  gender: 'child',
  description:  {
    pt: "Roupas coloridas e unissex",
    en: "Colorfull and unissex clothes",
    es: "Ropa colorida y unissex",
    it: "Abiti colorati e unissex"
  },
  price: 12,
  dateStart: '07/09/2020',
  dateEnd: '11/09/2020',
  sign: '£',
  language: 'en'},
{ id: 155,
  url:'image/munique-c-02.jpg',
  city: 'Munich, Alemanha',
  gender: 'child',
   description:  {
    pt: "Charme, delicadeza e diversão",
    en: "Charm, delicate and fun",
    es: "Encanto, delicado y divertido",
    it: "Fascino, delicato e divertente"
  },
  price: 6,
  dateStart: '10/09/2020',
  dateEnd: '15/09/2020',
  sign: '£',
  language: 'en'},
{ id: 156,
  url:'image/munique-c-03.jpg',
  city: 'Munich, Alemanha',
  gender: 'child',
  description:  {
    pt: "Artesanal. delicado e doce",
    en: "Handmade, delicate and sweet",
    es: "Hecho a mano, delicado y dulce",
    it: "Fatto a mano, delicato e dolce"
  },
  price: 59,
  dateStart: '12/09/2020',
  dateEnd: '18/09/2020',
  sign: '£',
  language: 'en'},
{ id: 157,
  url:'image/munique-f-01.jpg',
  city: 'Munich, Alemanha',
  gender: 'female',
  description:  {
    pt: "Charme, elegancia e conforto",
    en: "charm, fancy and comfortable",
    es: "encanto, elegante y confortable",
    it: "Affascinante, elegante e confortevole"
  },
  price: 17,
  dateStart: '03/09/2020',
  dateEnd: '07/09/2020',
  sign: '£',
  language: 'en'},
{ id: 158,
  url:'image/munique-f-02.jpg',
  city: 'Munich, Alemanha',
  gender: 'female',
  description:  {
    pt: "Moderno, artesanal e elegante",
    en: "Modern, handmade and elegant",
    es: "Moderno, artesanal y elegante",
    it: "Moderno, fatto a mano ed elegante"
  },
  price: 56,
  dateStart: '13/09/2020',
  dateEnd: '19/09/2020',
  sign: '£',
  language: 'en'},
{ id: 159,
  url:'image/munique-f-03.jpg',
  city: 'Munich, Alemanha',
  gender: 'female',
   description:  {
    pt: "Confortável, moderno e charmoso",
    en: "Comfortable, modern and charm",
    es: "Cómodo, moderno y con encanto",
    it: "Confortevole, moderno e affascinante"
  },
  price: 23,
  dateStart: '15/09/2020',
  dateEnd: '19/09/2020',
  sign: '£',
  language: 'en'},
{ id: 160,
  url:'image/munique-m-01.jpg',
  city: 'Munich, Alemanha',
  gender: 'male',
  description:  {
    pt: "Confortável e moderno",
    en: "Comfortable and modern",
    es: "Cómodo y moderno",
    it: "Confortevole e moderno"
  },
  price: 32,
  dateStart: '04/09/2020',
  dateEnd: '09/09/2020',
  sign: '£',
  language: 'en'},
{ id: 161,
  url:'image/munique-m-02.jpg',
  city: 'Munich, Alemanha',
  gender: 'male',
  description:  {
    pt: "Estilo e elegancia",
    en: "Elegant and style",
    es: "Elegante y estilo",
    it: "Elegante e di stile"
  },
  price: 32,
  dateStart: '08/08/2020',
  dateEnd: '13/08/2020',
  sign: '£',
  language: 'en'},


  

 ];